
package:
  name: mercat
  version: "0.1"

source:
  git_url: https://github.com/pnnl/mercat.git
#  git_rev: 0.1

build:
  number: 0


requirements:
  build:
    - python
    - scikit-bio
    - prodigal
    - trimmomatic
    - dask
    - setuptools
    - pandas
    - numpy
    - humanize
    - plotly
    - psutil
    - joblib

  run:
    - python
    - scikit-bio
    - prodigal
    - trimmomatic
    - dask
    - setuptools
    - pandas
    - numpy
    - humanize
    - plotly
    - psutil
    - joblib

#test:
  # Python imports
  # imports:
   # - mercat

  #commands:
  #  - $PREFIX/mercat.py -h

about:
  home:
  license: BSD
  summary: 'Mercat: a versatile counter and diversity estimator for data base independent property analysis obtained from whole community sequencing data.'
  license_family: BSD

extra:
  recipe-maintainers:
    - ajaypanyala
